$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$sidebarPath = Join-Path $repoRoot "_sidebar.md"

$excludedRootDirectories = @(
    ".git",
    "docs",
    "scripts"
)

$rootSections = @(
    @{ RelativePath = "Expression"; Label = "Expression" },
    @{ RelativePath = "Examples"; Label = "Examples" },
    @{ RelativePath = "Language"; Label = "Language" },
    @{ RelativePath = "IR"; Label = "IR" },
    @{ RelativePath = "Libraries"; Label = "Libraries" },
    @{ RelativePath = "Profiles"; Label = "Profiles" },
    @{ RelativePath = "IDE"; Label = "IDE" },
    @{ RelativePath = "Conformance"; Label = "Conformance" },
    @{ RelativePath = "Implementations/Reference"; Label = "Reference Implementation" },
    @{ RelativePath = "Roadmap"; Label = "Roadmap" },
    @{ RelativePath = "Strategy/Heilmeier"; Label = "Strategy" }
)

$preferredRootDocs = @(
    @{ File = "GOVERNANCE.md"; Label = "Governance" },
    @{ File = "CONTRIBUTING.md"; Label = "Contributing" },
    @{ File = "CLA.md"; Label = "CLA" }
)

function Convert-ToRelativeRepoPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FullPath
    )

    return $FullPath.Substring($repoRoot.Length + 1).Replace("\", "/")
}

function Convert-ToDocsifyHref {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RelativePath
    )

    if ($RelativePath -eq "Readme.md") {
        return "/"
    }

    $segments = $RelativePath -split "/"
    $encodedSegments = foreach ($segment in $segments) {
        [Uri]::EscapeDataString($segment)
    }

    return "/" + ($encodedSegments -join "/")
}

function Format-Label {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    return $Name.Replace("_", " ")
}

function Find-ReadmeFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DirectoryPath
    )

    return Get-ChildItem -LiteralPath $DirectoryPath -File |
        Where-Object { $_.Name -ieq "Readme.md" -or $_.Name -ieq "README.md" } |
        Select-Object -First 1
}

function Test-DirectoryContainsMarkdown {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DirectoryPath
    )

    return [bool](Get-ChildItem -LiteralPath $DirectoryPath -Recurse -File -Filter *.md | Select-Object -First 1)
}

function Get-OrderedDirectories {
    param(
        [System.IO.DirectoryInfo[]]$Directories
    )

    if (-not $Directories) {
        return @()
    }

    return $Directories | Sort-Object { $_.Name.ToLowerInvariant() }
}

function Add-DirectorySidebarSection {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DirectoryPath,
        [Parameter(Mandatory = $true)]
        [int]$Depth,
        [string]$DisplayLabel
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $relativeDirectory = Convert-ToRelativeRepoPath -FullPath $DirectoryPath
    $directoryName = Split-Path -Path $DirectoryPath -Leaf
    $indent = "  " * $Depth
    $readme = Find-ReadmeFile -DirectoryPath $DirectoryPath
    $sectionLabel = if ($DisplayLabel) { $DisplayLabel } else { Format-Label -Name $directoryName }

    if ($readme) {
        $href = Convert-ToDocsifyHref -RelativePath (Convert-ToRelativeRepoPath -FullPath $readme.FullName)
        $lines.Add("$indent- [$sectionLabel]($href)")
    } else {
        $lines.Add("$indent- $sectionLabel")
    }

    $markdownFiles = Get-ChildItem -LiteralPath $DirectoryPath -File -Filter *.md |
        Where-Object { -not $readme -or $_.FullName -ne $readme.FullName } |
        Sort-Object { $_.Name.ToLowerInvariant() }

    foreach ($file in $markdownFiles) {
        $fileLabel = Format-Label -Name ([System.IO.Path]::GetFileNameWithoutExtension($file.Name))
        $fileHref = Convert-ToDocsifyHref -RelativePath (Convert-ToRelativeRepoPath -FullPath $file.FullName)
        $lines.Add("$indent  - [$fileLabel]($fileHref)")
    }

    $childDirectories = Get-ChildItem -LiteralPath $DirectoryPath -Directory |
        Where-Object { Test-DirectoryContainsMarkdown -DirectoryPath $_.FullName }

    foreach ($childDirectory in (Get-OrderedDirectories -Directories $childDirectories)) {
        $childLines = Add-DirectorySidebarSection -DirectoryPath $childDirectory.FullName -Depth ($Depth + 1)
        foreach ($childLine in $childLines) {
            $lines.Add($childLine)
        }
    }

    return $lines
}

$sidebarLines = New-Object System.Collections.Generic.List[string]
$sidebarLines.Add("<!-- Auto-generated by scripts/build-sidebar.ps1 -->")
$sidebarLines.Add("")
$sidebarLines.Add("- [Home](/)")

$rootSectionDirectories = @(
foreach ($section in $rootSections) {
    $fullPath = Join-Path $repoRoot $section.RelativePath
    if ((Test-Path -LiteralPath $fullPath) -and (Test-DirectoryContainsMarkdown -DirectoryPath $fullPath)) {
        [PSCustomObject]@{
            FullPath = $fullPath
            Label = $section.Label
        }
    }
}
) | Where-Object { $_ -and $_.FullPath }

foreach ($directory in $rootSectionDirectories) {
    $sectionLines = Add-DirectorySidebarSection -DirectoryPath $directory.FullPath -Depth 0 -DisplayLabel $directory.Label
    foreach ($sectionLine in $sectionLines) {
        $sidebarLines.Add($sectionLine)
    }
}

foreach ($rootDoc in $preferredRootDocs) {
    $rootDocPath = Join-Path $repoRoot $rootDoc.File
    if (-not (Test-Path -LiteralPath $rootDocPath)) {
        continue
    }

    $label = $rootDoc.Label
    $href = Convert-ToDocsifyHref -RelativePath $rootDoc.File
    $sidebarLines.Add("- [$label]($href)")
}

$sidebarLines | Set-Content -LiteralPath $sidebarPath -Encoding UTF8
Write-Host "Sidebar rebuilt at $sidebarPath"
